# Generated by Django 6.0.7 on 2026-07-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='password',
            field=models.CharField(blank=True, help_text='Password for private posts (hashed on save).', max_length=128),
        ),
        migrations.AddField(
            model_name='post',
            name='private',
            field=models.BooleanField(default=False, help_text='Require a password to view this post.'),
        ),
    ]
